import type { Activity, Course, Semester } from "./types";

export const SEED_SEMESTER: Semester = {
  id: "sem-2026-2",
  name: "2026-2",
  type: "semestral",
  startDate: "2026-08-04",
  endDate: "2026-12-05",
  isActive: true,
  cortes: [
    {
      index: 0,
      name: "Corte 1",
      startDate: "2026-08-04",
      endDate: "2026-09-19",
      weight: 33,
    },
    {
      index: 1,
      name: "Corte 2",
      startDate: "2026-09-22",
      endDate: "2026-10-31",
      weight: 33,
    },
    {
      index: 2,
      name: "Corte 3",
      startDate: "2026-11-03",
      endDate: "2026-12-05",
      weight: 34,
    },
  ],
};

const emptyCortes = (grades: Array<number | null>) =>
  grades.map((grade, index) => ({ index, grade }));

export const SEED_COURSES: Course[] = [
  {
    id: "curso-calculo",
    semesterId: "sem-2026-2",
    name: "Cálculo Integral",
    code: "MAT-204",
    professor: "Dra. Helena Ríos",
    color: "#2C4A5E",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 4,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([3.8, null, null]),
    schedule: [
      { id: "sl-calc-1", day: 0, startTime: "07:00", endTime: "09:00", room: "B-204" },
      { id: "sl-calc-2", day: 2, startTime: "07:00", endTime: "09:00", room: "B-204" },
    ],
  },
  {
    id: "curso-fisica",
    semesterId: "sem-2026-2",
    name: "Física Mecánica",
    code: "FIS-102",
    professor: "Ing. Pablo Merino",
    color: "#3D5340",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 4,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([4.2, null, null]),
    schedule: [
      { id: "sl-fis-1", day: 1, startTime: "09:00", endTime: "11:00", room: "Lab 3" },
      { id: "sl-fis-2", day: 3, startTime: "09:00", endTime: "11:00", room: "Lab 3" },
    ],
  },
  {
    id: "curso-poo",
    semesterId: "sem-2026-2",
    name: "Programación Orientada a Objetos",
    code: "SIS-210",
    professor: "MSc. Laura Cano",
    color: "#6B3E3A",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 3,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([4.5, null, null]),
    schedule: [
      { id: "sl-poo-1", day: 0, startTime: "14:00", endTime: "16:00", room: "C-110" },
      { id: "sl-poo-2", day: 2, startTime: "14:00", endTime: "16:00", room: "C-110" },
      { id: "sl-poo-3", day: 4, startTime: "14:00", endTime: "16:00", room: "C-110" },
    ],
  },
  {
    id: "curso-algebra",
    semesterId: "sem-2026-2",
    name: "Álgebra Lineal",
    code: "MAT-203",
    professor: "Dr. Andrés Pineda",
    color: "#3E5560",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 3,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([3.5, null, null]),
    schedule: [
      { id: "sl-alg-1", day: 1, startTime: "14:00", endTime: "16:00", room: "A-12" },
      { id: "sl-alg-2", day: 3, startTime: "14:00", endTime: "16:00", room: "A-12" },
    ],
  },
  {
    id: "curso-com",
    semesterId: "sem-2026-2",
    name: "Comunicación Oral y Escrita",
    code: "HUM-110",
    professor: "Lic. Sofía Vargas",
    color: "#5C4A38",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 2,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([4.0, null, null]),
    schedule: [{ id: "sl-com-1", day: 4, startTime: "09:00", endTime: "11:00", room: "H-03" }],
  },
  {
    id: "curso-const",
    semesterId: "sem-2026-2",
    name: "Constitución Política",
    code: "DER-101",
    professor: "Abg. Camilo Restrepo",
    color: "#3A5550",
    type: "semestral",
    startDate: "2026-08-04",
    endDate: "2026-12-05",
    credits: 2,
    notes: "",
    finalGrade: null,
    cortes: emptyCortes([4.8, null, null]),
    schedule: [{ id: "sl-const-1", day: 5, startTime: "08:00", endTime: "10:00", room: "Auditorio" }],
  },
];

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    courseId: "curso-calculo",
    name: "Taller 4 — técnicas de integración",
    description: "Sustitución trigonométrica y fracciones parciales.",
    dueDate: "2026-09-08",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-20",
  },
  {
    id: "act-2",
    courseId: "curso-fisica",
    name: "Quiz de cinemática",
    description: "Movimiento parabólico y relativa.",
    dueDate: "2026-09-09",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-25",
  },
  {
    id: "act-3",
    courseId: "curso-fisica",
    name: "Informe laboratorio 2",
    description: "Caída libre y registro de datos.",
    dueDate: "2026-09-10",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-28",
  },
  {
    id: "act-4",
    courseId: "curso-poo",
    name: "Entrega sprint 2",
    description: "Herencia, interfaces y pruebas unitarias.",
    dueDate: "2026-09-11",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-18",
  },
  {
    id: "act-5",
    courseId: "curso-algebra",
    name: "Taller de espacios vectoriales",
    description: "Base, dimensión e independencia lineal.",
    dueDate: "2026-09-12",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-22",
  },
  {
    id: "act-6",
    courseId: "curso-com",
    name: "Ensayo argumentativo",
    description: "1.500 palabras, citas APA.",
    dueDate: "2026-09-15",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-30",
  },
  {
    id: "act-7",
    courseId: "curso-calculo",
    name: "Parcial corte 1",
    description: "Integrales definidas y teorema fundamental.",
    dueDate: "2026-09-17",
    done: false,
    corteIndex: 0,
    grade: null,
    createdAt: "2026-08-10",
  },
  {
    id: "act-8",
    courseId: "curso-const",
    name: "Lectura capítulo 4",
    description: "Rama judicial y control de constitucionalidad.",
    dueDate: "2026-09-06",
    done: true,
    corteIndex: 0,
    grade: 5,
    createdAt: "2026-08-15",
  },
  {
    id: "act-9",
    courseId: "curso-poo",
    name: "Lectura de patrones",
    description: "Factory, Strategy y Observer.",
    dueDate: "2026-09-04",
    done: true,
    corteIndex: 0,
    grade: 4.5,
    createdAt: "2026-08-12",
  },
  {
    id: "act-10",
    courseId: "curso-algebra",
    name: "Quices semanales",
    description: "Promedio de los cinco primeros quices.",
    dueDate: "2026-09-05",
    done: true,
    corteIndex: 0,
    grade: 3.8,
    createdAt: "2026-08-08",
  },
  {
    id: "act-11",
    courseId: "curso-poo",
    name: "Proyecto final — propuesta",
    description: "Documento de alcance y diagrama de clases.",
    dueDate: "2026-10-08",
    done: false,
    corteIndex: 1,
    grade: null,
    createdAt: "2026-09-01",
  },
  {
    id: "act-12",
    courseId: "curso-fisica",
    name: "Parcial corte 2",
    description: "Leyes de Newton y trabajo-energía.",
    dueDate: "2026-10-20",
    done: false,
    corteIndex: 1,
    grade: null,
    createdAt: "2026-09-01",
  },
];
