/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorarioRouteImport } from './routes/horario'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as PeriodoRouteImport } from './routes/periodo'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as MateriasIdRouteImport } from './routes/materias.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorarioRoute = HorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodoRoute = PeriodoRouteImport.update({
  id: '/periodo',
  path: '/periodo',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasIdRoute = MateriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MateriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRouteWithChildren
  '/periodo': typeof PeriodoRoute
  '/tareas': typeof TareasRoute
  '/materias/$id': typeof MateriasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRouteWithChildren
  '/periodo': typeof PeriodoRoute
  '/tareas': typeof TareasRoute
  '/materias/$id': typeof MateriasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRouteWithChildren
  '/periodo': typeof PeriodoRoute
  '/tareas': typeof TareasRoute
  '/materias/$id': typeof MateriasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/horario' | '/materias' | '/periodo' | '/tareas' | '/materias/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/horario' | '/materias' | '/periodo' | '/tareas' | '/materias/$id'
  id:
    | '__root__'
    | '/'
    | '/horario'
    | '/materias'
    | '/periodo'
    | '/tareas'
    | '/materias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorarioRoute: typeof HorarioRoute
  MateriasRoute: typeof MateriasRouteWithChildren
  PeriodoRoute: typeof PeriodoRoute
  TareasRoute: typeof TareasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horario': {
      id: '/horario'
      path: '/horario'
      fullPath: '/horario'
      preLoaderRoute: typeof HorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodo': {
      id: '/periodo'
      path: '/periodo'
      fullPath: '/periodo'
      preLoaderRoute: typeof PeriodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias/$id': {
      id: '/materias/$id'
      path: '/$id'
      fullPath: '/materias/$id'
      preLoaderRoute: typeof MateriasIdRouteImport
      parentRoute: typeof MateriasRoute
    }
  }
}

interface MateriasRouteChildren {
  MateriasIdRoute: typeof MateriasIdRoute
}

const MateriasRouteChildren: MateriasRouteChildren = {
  MateriasIdRoute: MateriasIdRoute,
}

const MateriasRouteWithChildren = MateriasRoute._addFileChildren(
  MateriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorarioRoute: HorarioRoute,
  MateriasRoute: MateriasRouteWithChildren,
  PeriodoRoute: PeriodoRoute,
  TareasRoute: TareasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
